services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 6585qwer
      MYSQL_DATABASE: ottshare
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: ottshare-image
    container_name: ottshare-container
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - app-network
    environment:
      - APP_REDIS_HOST=redis-container
      - APP_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
