version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 6585qwer
      MYSQL_DATABASE: ottshare
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: ottshare-image
    container_name: ottshare-container
    ports:
      - "8081:8080"
    environment:
      APP_DB_USERNAME: root
      APP_DB_PASSWORD: 6585qwer
      APP_JWT_SECRET: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
      APP_COOLSMS_API_KEY: NCSNE0EKVTZAUCCY
      APP_COOLSMS_API_SECRET: V1SHVAWC0NI4DN9YE1LP3FTN12WSBHG
      APP_GOOGLE_CLIENT_ID: 680439794424-cpjpvio9atllukjnvb52aq9lkg97oa03.apps.googleusercontent.com
      APP_REDIS_HOST:
      APP_REDIS_PORT: 6379
      APP_DB_URL: jdbc:mysql://mysql-container:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: ottshare
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
