services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 6585qwer
      MYSQL_DATABASE: ottshare
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: ottshare-image
    container_name: ottshare-container
    ports:
      - "8081:8080"
    env_file:
      - ../.env
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
