spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 680439794424-cpjpvio9atllukjnvb52aq9lkg97oa03.apps.googleusercontent.com
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        security=DEBUG:

redis:
  host: localhost
  port: 6379
  repositories:
    enabled: false

coolsms:
  api:
    key: "NCSNE0EKVTZAUCCY"
    secret: "V1SHVAWC0NI4DN9YE1LP3FTN12WSBHG6"
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  expiration: 3600