spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 680439794424-cpjpvio9atllukjnvb52aq9lkg97oa03.apps.googleusercontent.com
            scope:
              - email
              - profile
#          facebook:
#            client-id:
#            client-secret:
#            scope:
#              - email
#              - public_profile
#          naver:
#            client-id: CT9aIg0cL7APRjqGOBVr
#            client-secret: hl1MonEQWz
#            scope:
#              - name
#              - email
#            client-name: naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
logging:
  level:
    org:
      springframework:
        security=DEBUG:

redis:
  host: localhost
  port: 6379
  repositories:
    enabled: false

coolsms:
  api:
    key: "NCSNE0EKVTZAUCCY"
    secret: "V1SHVAWC0NI4DN9YE1LP3FTN12WSBHG6"
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true