# application-local.yml
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}