spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${APP_GOOGLE_CLIENT_ID}
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        security: DEBUG

coolsms:
  api:
    key: ${APP_COOLSMS_API_KEY}
    secret: ${APP_COOLSMS_API_SECRET}

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true

jwt:
  secret: ${APP_JWT_SECRET}
  expiration: 3600
  refreshExpiration: 86400
