# application-prod.yml
spring:
  data:
    redis:
      host: redis-container
      port: 6379
  datasource:
    url: jdbc:mysql://mysql-container:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 6585qwer
